// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHc-6xiKtSdJvVMG7zs3gBxLcDXqnTmEI',
    appId: '1:872438871135:web:8367320485646d217c57ea',
    messagingSenderId: '872438871135',
    projectId: 'forex-signals-daily-9ca6e',
    authDomain: 'forex-signals-daily-9ca6e.firebaseapp.com',
    databaseURL: 'https://forex-signals-daily-9ca6e-default-rtdb.firebaseio.com',
    storageBucket: 'forex-signals-daily-9ca6e.appspot.com',
    measurementId: 'G-VCYT97RFG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOig4cYU797XWwLW1Z3fgRCcxYo_n-kOw',
    appId: '1:872438871135:android:43be1299d6f385d97c57ea',
    messagingSenderId: '872438871135',
    projectId: 'forex-signals-daily-9ca6e',
    databaseURL: 'https://forex-signals-daily-9ca6e-default-rtdb.firebaseio.com',
    storageBucket: 'forex-signals-daily-9ca6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Lw3NcsFhI_1mop74y3tow_u6lHZQ2aw',
    appId: '1:872438871135:ios:3bb450d21efdb65d7c57ea',
    messagingSenderId: '872438871135',
    projectId: 'forex-signals-daily-9ca6e',
    databaseURL: 'https://forex-signals-daily-9ca6e-default-rtdb.firebaseio.com',
    storageBucket: 'forex-signals-daily-9ca6e.appspot.com',
    androidClientId: '872438871135-p1oc6spppcd9ui9nei6m7mk24cvfakgf.apps.googleusercontent.com',
    iosClientId: '872438871135-kr49p3au7ci8bi4elb55oduu9a3bp537.apps.googleusercontent.com',
    iosBundleId: 'com.kluster.forexsignals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Lw3NcsFhI_1mop74y3tow_u6lHZQ2aw',
    appId: '1:872438871135:ios:c52f29cecc3e74907c57ea',
    messagingSenderId: '872438871135',
    projectId: 'forex-signals-daily-9ca6e',
    databaseURL: 'https://forex-signals-daily-9ca6e-default-rtdb.firebaseio.com',
    storageBucket: 'forex-signals-daily-9ca6e.appspot.com',
    androidClientId: '872438871135-p1oc6spppcd9ui9nei6m7mk24cvfakgf.apps.googleusercontent.com',
    iosClientId: '872438871135-lpsactiaqbgpvii93vctg76n8s7ie7qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3ForexSignalsDaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHc-6xiKtSdJvVMG7zs3gBxLcDXqnTmEI',
    appId: '1:872438871135:web:9fb3dae5b7359f457c57ea',
    messagingSenderId: '872438871135',
    projectId: 'forex-signals-daily-9ca6e',
    authDomain: 'forex-signals-daily-9ca6e.firebaseapp.com',
    databaseURL: 'https://forex-signals-daily-9ca6e-default-rtdb.firebaseio.com',
    storageBucket: 'forex-signals-daily-9ca6e.appspot.com',
    measurementId: 'G-TXFYE0MK2E',
  );
}
